### ISSUE TITLE
Playground keeps freezing

### ISSUE THREAD

**Issue by sasq64** [yhirose/cpp-peglib#107] opened 2020-05-26 20:11 UTC
After a while the editor freezes and even reloading doesn't help.

I'm trying to implement recursive curly brace parsing so that

```
!meta "x" {
   !meta "y" {
    stuff
  }
}
```
Can be parsed by something like

```
Meta <- MetaName _ MetaArgs Block?
MetaName <- '!' Symbol
MetaArgs <- MetaArg (',' MetaArg)* ','?
MetaArg <- String / Expression

Block <- _ '{' BlockContents '}'
BlockContents <- SkipLine*
SkipLine <- (SkipMeta / SkipAny)
SkipMeta <- MetaName _ MetaArgs Block? EOL
SkipAny <- !('}' / EOL)* EOL
```
Have been trying many different ways to skip lines in the block but no luck so far.
Any pointers?

**Comment by yhirose** [comment] 2020-05-26 22:07
@sasq64, thanks for the feedback. Could you give me the whole grammar that causes the freeze? I'll take a loot at it when I have time.

I have actually experiences such crash on the playground a couple of times. On both cases, my grammars had problem which caused infinite loops. So I made the following infinite loop detector. (You can also see some unit test cases with `[infinite loop]` tag. in `test/test.cc`.)

https://github.com/yhirose/cpp-peglib/blob/19c6c2615c0265f917746a2c75fd6cb39388fb9f/peglib.h#L1958

Anyway, your may have found another case that causes an infinite loop that cpp-peglib currently cannot detect. Once I get your grammar, I'll look into it.

In order to fix the freeze on playground, if you are using Chrome, please go to `chrome://settings/siteData`, find `yhirose.github.io`, and clear the Local Storage data.

**Comment by yhirose** [comment] 2020-06-01 03:51
@sasq64, any response?

**Comment by sasq64** [comment] 2020-06-01 14:08
My grammar is pretty messy and I haven't reduced it to something simple yet. Will try tomorrow.

But I also notice that often when the grammar fails to match what it wants it goes into an infinite loop in my normal program?

**Comment by sasq64** [comment] 2020-06-01 19:36
So for instance the parsing never ends for the string `:a:` with this grammar, when I run it in C++.

The playground doesn't freeze here though, it just returns no result. It doesn't complain on the
grammar itself and it works for normal cases.

With the `:a:` string, `MetaArgs` doesn't match so it falls back to `Program` which was not my intention, and it gets stuck in `OpLine` which gets matched with 0 semantic arguments and keeps repeating...

```
Root <- RootExpression / RootDefinition / RootList / Program

RootExpression <- ':x:' Expression
RootDefinition <- ':d:' FnDef
RootList <- ':a:' MetaArgs

Program <- (Line (EOL / ''))*
Line <- (MacroCall / AssignLine / OpLine) _? LineComment?
AssignLine <- _? ('*' / Assignee) _? '=' Expression
Assignee <- Symbol _?

OpLine <- ~Label? _? (MacroCall / Test / Meta / Instruction)?
Instruction <- Opcode Arg?
MacroCall <- Call

Meta <- MetaName _  MetaText Block? (_ Symbol _ Block)*
MetaText <- (!(EOL / '}' / '{' / LineComment) .)*
MetaName <- '!' Symbol
MetaArgs <- MetaArg (_ ',' MetaArg)* ','?
MetaArg <- String / Expression / Call

Test <- "!test" _ TestName _ Block
TestName <- Symbol

FnDef <- FnName '(' FnArgs ')'
FnName <- Symbol
FnArgs <- (FnArg (',' FnArg)*)?
FnArg <- _? Symbol _?

Block <- EOL? _ '{' BlockContents '}'
BlockContents <- SkipProgram

SkipProgram <- (SkipLine EOL)* SkipLine?
SkipLine <- SkipLabel? _? (SkipMeta / SkipInstruction)? _? LineComment?
SkipLabel <- (_? DotSymbol ':') / (DotSymbol (_ / &EOL))
SkipInstruction <- (!(EOL / '}') .)*
SkipMeta <- MetaName _  (!(EOL / '}' / '{') .)* Block?

String <- _ ["] StringContents ["] _
StringContents <- (!["] .)*

Assign <- Symbol '=' Expression

Label <- (_? DotSymbol ':') / (DotSymbol (_ / &EOL))

Arg <- _ (LabelRef / Acc / Imm / IndY / IndX / Ind / AbsX / AbsY / Abs)

IndX <- '(' Expression (TailX0 / TailX1)
TailX0 <- ')' _? ',' _? 'X'i
TailX1 <- ',' _? 'X'i _? ')'

IndY <- '(' Expression (TailY0 / TailY1)
TailY0 <- ')' _? ',' _? 'Y'i
TailY1 <- ',' _? 'Y'i _? ')'

Ind <- '(' Expression ')' &(!Operator)
Acc <- 'a'i &(!Symbol)
Abs <- Expression
AbsX <- Expression ',' _? 'X'i
AbsY <- Expression ',' _? 'Y'i
Imm <- '#' Expression

LabelRef <- '-'+ / '+'+

Opcode <- Symbol

HexNum <- ('$' / '0x') [0-9a-fA-F]+
Octal <- '0o' [0-7]+
Binary <- '0b' [01]+
Decimal <- [0-9]+
Number <-  HexNum / Binary / Octal / Decimal

LineComment <- ';' (!EOL .)* &EOL

~_ <- [ \t]*

Symbol <- [_A-Za-z] [_A-Za-z0-9]*
DotSymbol <- LabelChar / ([._A-Za-z] [_A-Za-z0-9]*)

LabelChar <- '-' / '+' / '$'


EOL <- '\r\n' / '\r' / '\n'
EOT <- !.

Expression  <- Atom (Operator Atom)* {
                         precedence
                           L &&
                           L ||
                           L |
                           L ^
                           L &
                           L == !=
                           L < > <= >=
                           L <=>
                           L << >>
                           L - +
                           L / * % \
                       }


Atom <- _? (Star / Unary / Number /
        FnCall / Index / Variable / '(' Expression ')') _?

Star <- '*'

Index <- Variable '[' Expression (':' Expression)? ']'

Unary <- UnOp Atom
UnOp <- ('!' / '~' / '-' / '<' / '>' )
FnCall <- Call
Call <- CallName '(' CallArgs ')'
CallName <- Symbol
CallArgs <- (CallArg (',' CallArg)*)?
CallArg <- String / Expression
Operator <-  
        '&&' / '||' / '<<' / '>>' / '==' / '!=' /
        '+' / '-' / '*' / '/' / '%' / '\\' /
        '|' / '^' / '&' / '<' / '>'
Variable <- '.'? (Symbol '.')* Symbol
```

**Comment by yhirose** [comment] 2020-06-01 21:25
@sasq64, your comment explanations that parsing your grammar doesn't fall into the infinite loop, but parsing the source text `:a:` with this grammar causes the infinite loop. If so, whatever PEG library you use, you will have the same problem. That's not a problem in cpp-peglib. So I'll close it.

Good news is that you have already noticed that the problem is caused by `OpLine`.
You can get more information by tracing with `peglint --trace`. Here are the steps to do it:

1) Save the grammar to `a.peg`
2) Run `peglint a.peg --source ":a:" --trace`

Hope it helps your debugging the grammar!

**Closed** 2020-06-01 23:47 UTC

**Comment by yhirose** [comment] 2020-06-01 23:54
@sasq64, I changed cpp-peglib to detect such a grammar. If you put your grammar in the latest playground (v0.1.7), you now see the error message "1:54 infinite loop is detected in 'Program'".

**Comment by sasq64** [comment] 2020-06-02 06:33
Thank you so much!

My problem seems to come from my `(EOL / '')` rule... I have assumed that `''` means end-of-text, since I want to match also the last line in the file even if it has no EOL.

Is there another way to do this?

**Comment by sasq64** [comment] 2020-06-02 06:42
Actually I found https://github.com/xored/peg/blob/master/docs/grammar-tips.md which give some tips, and helped me understand that a loop that can match nothing is a problem, and the `''` must be moved out of the loop.

**Comment by sasq64** [comment] 2020-06-02 07:14
So
`Program <- (Line (EOL))* (Line EOT)?`
avoids it, except now the action of my last _Line_ is called twice... (which is correct, but I generate output from actions so I need to figure out how to avoid it).
