### ISSUE TITLE
return null grammar

### ISSUE THREAD

**Issue by Quetzalfir** [yhirose/cpp-peglib#154] opened 2021-03-05 19:14 UTC
I have been using the library for a while, and the following grammar already worked perfectly in previous versions, in this latest version the same grammar returns a nullptr, in the internal state of the parser object.

Grammar:

         COLOR	          <- RGB / RGBA / HSL / HSLA / HEX_COLOR / NAMED_COLOR

         NAMED_COLOR	  <- "aliceblue" | "antiquewhite" | "aqua" | "aquamarine" | "azure" | "beige" |
                                 "bisque" | "black" | "blanchedalmond" | "blue" | "blueviolet" | "brown" | "burlywood" |
                                 "cadetblue" | "chartreuse" | "chocolate" | "coral" | "cornflowerblue" | "cornsilk" |
                                 "crimson" | "cyan" | "darkblue" | "darkcyan" | "darkgoldenrod" | "darkgray" | "darkgrey" |
                                 "darkgreen" | "darkkhaki" | "darkmagenta" | "darkolivegreen" | "darkorange" | "darkorchid" |
                                 "darkred" | "darksalmon" | "darkseagreen" | "darkslateblue" | "darkslategray" | "darkslategrey" |
                                 "darkturquoise" | "darkviolet" | "deeppink" | "deepskyblue" | "dimgray" | "dimgrey" | "dodgerblue" |
                                 "firebrick" | "floralwhite" | "forestgreen" | "fuchsia" | "gainsboro" | "ghostwhite" | "gold" |
                                 "goldenrod" | "gray" | "grey" | "green" | "greenyellow" | "honeydew" | "hotpink" | "indianred " |
                                 "indigo " | "ivory" | "khaki" | "lavender" | "lavenderblush" | "lawngreen" | "lemonchiffon" |
                                 "lightblue" | "lightcoral" | "lightcyan" | "lightgoldenrodyellow" | "lightgray" | "lightgrey" |
                                 "lightgreen" | "lightpink" | "lightsalmon" | "lightseagreen" | "lightskyblue" | "lightslategray" |
                                 "lightslategrey" | "lightsteelblue" | "lightyellow" | "lime" | "limegreen" | "linen" |
                                 "magenta" | "maroon" | "mediumaquamarine" | "mediumblue" | "mediumorchid" | "mediumpurple" |
                                 "mediumseagreen" | "mediumslateblue" | "mediumspringgreen" | "mediumturquoise" | "mediumvioletred" |
                                 "midnightblue" | "mintcream" | "mistyrose" | "moccasin" | "navajowhite" | "navy" | "oldlace" |
                                 "olive" | "olivedrab" | "orange" | "orangered" | "orchid" | "palegoldenrod" | "palegreen" |
                                 "paleturquoise" | "palevioletred" | "papayawhip" | "peachpuff" | "peru" | "pink" | "plum" |
                                 "powderblue" | "purple" | "rebeccapurple" | "red" | "rosybrown" | "royalblue" | "saddlebrown" |
                                 "salmon" | "sandybrown" | "seagreen" | "seashell" | "sienna" | "silver" | "skyblue" | "slateblue" |
                                 "slategray" | "slategrey" | "snow" | "springgreen" | "steelblue" | "tan" | "teal" | "thistle" |
                                 "tomato" | "turquoise" | "transparent" | "violet" | "wheat" | "white" | "whitesmoke" |
                                 "yellow" | "yellowgreen"

         HEX_COLOR            <- < '#' HEX_DIGIT{8} ' '? > /
                                 < '#' HEX_DIGIT{6} ' '? > /
                                 < '#' HEX_DIGIT{4} ' '? > /
                                 < '#' HEX_DIGIT{3} ' '? >

         RGB                  <- "rgb"  "(" PERCENTAGE{3} ('/' ALPHA_VALUE)? ')' /
                                 "rgb"  "(" NUMBER{3} ('/' ALPHA_VALUE)? ')' /
                                 "rgb"  "(" PERCENTAGE (',' PERCENTAGE){2} (',' ALPHA_VALUE)? ')' /
                                 "rgb"  "(" NUMBER (',' NUMBER){2} (',' ALPHA_VALUE)? ')'
         RGBA                 <- "rgba" "(" PERCENTAGE{3} ('/' ALPHA_VALUE)? ')' /
                                 "rgba" "(" NUMBER{3} ('/' ALPHA_VALUE)? ')' /
                                 "rgba" "(" PERCENTAGE (',' PERCENTAGE){2} (',' ALPHA_VALUE)? ')' /
                                 "rgba" "(" NUMBER (',' NUMBER){2} (',' ALPHA_VALUE)? ')'
         HSL                  <- "hsl"  "(" HUE PERCENTAGE{2} ('/' ALPHA_VALUE)? ')' /
                                 "hsl"  "(" HUE (',' PERCENTAGE){2} (',' ALPHA_VALUE)? ')'
         HSLA                 <- "hsla" "(" HUE PERCENTAGE{2} ('/' ALPHA_VALUE)? ')' /
                                 "hsla" "(" HUE (',' PERCENTAGE){2} (',' ALPHA_VALUE)? ')'

         ALPHA_VALUE          <- < PERCENTAGE / NUMBER >
         HUE                  <- ANGLE / NUMBER

         ANGLE                <- < NUMBER ANGLE_UNIT >
         ANGLE_UNIT           <- "deg" | "grad" | "rad" | "turn"

         PERCENTAGE           <- <NUMBER> '%'
         NUMBER               <- <FLOAT / INTEGER>
         FLOAT                <- ('+'|'-')? [0-9]* '.' [0-9]+
         INTEGER              <- ('+'|'-')? [0-9]+
         HEX_DIGIT	      <- [a-fA-F0-9]
         DIGIT		      <- [0-9]

         %whitespace          <-  [ \t\r\n]

the debug process take me into the funnction

    std::shared_ptr<Grammar> perform_core(const char *s, size_t n,
                                        const Rules &rules, std::string &start,
                                        Log log) {

    ...

    for (auto &[name, rule] : grammar) {
      if (!referenced.count(name)) {    // here the first rule, which is DIGIT returns 0 
        if (log) {
          auto line = line_info(s, rule.s_);
          auto msg = "'" + name + "' is not referenced.";
          log(line.first, line.second, msg);
        }
        ret = false;
      }
    }

    ...

**Comment by yhirose** [comment] 2021-03-05 20:02
@Quetzalfir, I implemented to disallow 'unreferenced rules'. I saved the above grammar to 145.peg and checked it with peglint. Here is the result:

```
> peglint 154.peg 
154.peg:56:6: 'DIGIT' is not referenced.
```

So the current reports `DIGIT` rule as the unreferenced error. If you comment out the line of `DIGIT`, it should work.

But I feel now that this enhancement is too strict, and will surprise a number of users...
I am thinking to change it to a warning, not an error, so that it won't break existing users' code.
Please let me know your thought.

**Comment by Quetzalfir** [comment] 2021-03-05 20:18
I have several grammars of which I took the most "complete" and copied the template and then I was completing it or adding rules according to the needs. I could remove the unused rules, the only thing that would be a little difficult is to go grammar by grammar and check which ones I don't use, maybe if there was a warning saying of a rule that is not used and announcing that it would improve the efficiency of the parser if it was removed. 

I guess there are other users who have something similar or maybe they have unused rules because in the future they plan to increase the grammar, to which I think the best option is to comment such a rule and so it would be easy to solve it and keep track of the rule without current use.

I updated the version without reading official documentation, hoping that I would not break anything. I guess the most viable option is to put the warning that the rule is not in use and the speed of the parser can be improved if it is removed.

**Comment by yhirose** [comment] 2021-03-05 22:05
@Quetzalfir, thanks for the detailed information. I can see the pain that caused by the change... I decided to report the 'unreferenced rule' as a warning, not an error and committed the fix. (I think this makes sense, because it is pretty much similar to the common 'unused variable' warning many compilers output.)

So we can leave unreferenced rules in grammars again, and your original grammar should work with the latest peglib.h. Only when we do grammar check with peglint or [PEG playground](https://yhirose.github.io/cpp-peglib/), we will see the warning.

Thanks for your help!

**Closed by yhirose** 2021-03-05 22:05 UTC
